# Generated by Django 5.1.4 on 2024-12-27 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_userkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessages',
            name='encrypted_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='chat_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserKey',
        ),
    ]
